name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  openjdk17:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-Xmx6G -XX:+UseG1GC"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Build project
        run: sbt test

      - name: Check Formatting
        run: sbt scalafmtCheckAll
